### ISSUE TITLE
Критерий защищенности канала утечки информации по цепям электропитания - просто текст без ссылок

### ISSUE THREAD

**Issue by almkuznetsov** [almkuznetsov/bmstudemo#1]
Надо найти ссылки откуда это взято

**Comment by nedomolkinaeyu** [comment]
сделала, плюсом добавила ссылки на эти статьи. Вопрос: нужны ли ссылки на статьи (они были только на сайте "Бюро научно-технической информации"

**Comment by almkuznetsov** [comment]
> сделала, плюсом добавила ссылки на эти статьи. Вопрос: нужны ли ссылки на статьи (они были только на сайте "Бюро научно-технической информации"

Ссылки это полезно, их стоит вставлять в карточку самой статьи, не обязательно рядом с каждой ссылкой писать
