### ISSUE TITLE
Лазерный канал, оформить цитаты

### ISSUE THREAD

**Issue by almkuznetsov** [almkuznetsov/bmstudemo#16]
В основной карточке по лазерному каналу цитата не выделена как цитата и не указана страница
В карточке защиты от лазера и карточке возможности прослушивания не указана страница откуда цитата

**Comment by nedomolkinaeyu** [comment]
выделила, как цитату
страница не может быть указана, так как эта статья на одной странице сайта (ссылка на сайт есть в карточке Хорев А.А.Технические каналы утечки информации.Классификация и хар-ка. Статья из журнала)

**Comment by almkuznetsov** [comment]
> 

У меня есть очень большое подозрение, что эта статья на самом деле вот эта - https://elibrary.ru/item.asp?id=13011605
Переименуй, тогда, наверное, на её официальное название - Хорев А. А. Технические каналы утечки акустической (речевой) информации. Специальная техника. – 2009. – №. 5. – С. 12-26.

**Comment by almkuznetsov** [comment]
Теперь получается что есть две карточки с одинаковыми ссылками на эту статью
![image](https://user-images.githubusercontent.com/96069812/190573306-85210ef4-233f-449f-b00e-97a7e6a974e4.jpeg)
Надо удалить старую и ссылки которые были на неё перевести на новую
