### ISSUE TITLE
В папке "Заметки" есть файл "Физический принцип", не привязанный ни к какому каналу

### ISSUE THREAD

**Issue by almkuznetsov** [almkuznetsov/bmstudemo#19]
На него нет никаких ссылок, но он же про какой-то конкретный канал? Или он просто потерялся и дублируется?
![image](https://user-images.githubusercontent.com/96069812/190385272-3b3a2bfc-6ae2-4bc7-94c4-bf264ef9bb16.jpeg)

**Comment by nedomolkinaeyu** [comment]
сделано

**Comment by nedomolkinaeyu** [comment]
проверила все у имеющихся каналов, видимо потерялся
удалила

**Comment by almkuznetsov** [comment]
Я на всякий случай перепроверил. Он дублировал карточку "Высокочастотное облучение", так что правильно, что удалила.
Решено в 15270ba4b52764d9e0b6179a73deb3808a0ab0b5
