### ISSUE TITLE
"Критерий защищенности НПТ" пустой файл

### ISSUE THREAD

**Issue by almkuznetsov** [almkuznetsov/bmstudemo#20]
В карточке "Предельное допустимое значение отношения величины изменения тока к средней величине потребления тока" по сути указан критерий защищенности - "Если указанное отношение не превышает предельного значения, эффективный прием по каналу НПТ невозможен."
Нужно добавить эту информацию и ссылку на "Предельно допустимое..." в "Критерий защищенности НПТ"
![image](https://user-images.githubusercontent.com/96069812/190385806-51565dcf-42a2-49f1-ab13-996699aa584c.jpeg)

**Comment by nedomolkinaeyu** [comment]
сделано
