### ISSUE TITLE
В режиме редактирования диаграммы PlantUML отображают syntax error

### ISSUE THREAD

**Issue by almkuznetsov** [almkuznetsov/bmstudemo#23]
Это не сильно большая проблема, поскольку в режиме просмотра они отображаются как должны, но всё же интересно, почему так происходит

**Comment by almkuznetsov** [comment]
![image](https://user-images.githubusercontent.com/96069812/190576450-a20a1832-4d1d-488e-bf47-aeb786ae0608.jpeg)

**Comment by dpetruh** [comment]
данная ошибка рассмотрена и описана в ишью #14

**Comment by almkuznetsov** [comment]
Дублирует #14
