### ISSUE TITLE
Не перенесены определения распределенной и сосредоточенной антенны

### ISSUE THREAD

**Issue by almkuznetsov** [almkuznetsov/bmstudemo#24]
![image](https://user-images.githubusercontent.com/96069812/190605813-b501b7c3-4ff3-4ed5-ab0b-0c48b5660b6f.jpeg)

**Comment by nedomolkinaeyu** [comment]
сделано

**Comment by almkuznetsov** [comment]
1. Им не проставлен тег "определение", поэтому они не отображаются в списке определений.
2. Можно в них поставить обратные ссылки типа "Это подвид [[случайная антенна]]"

**Comment by nedomolkinaeyu** [comment]
сделано
