### ISSUE TITLE
Переименовать имеющиеся каналы так, чтобы название отражало три основных элемента канала

### ISSUE THREAD

**Issue by almkuznetsov** [almkuznetsov/bmstudemo#26]
"Канал утечки ______(телекоммуникационной/акустической речевой) информации за счет _______ (физический принцип) со съемом ________ (способ съема)". Тогда пример канала:
- Канал утечки телекоммуникационной информации за счет ВЧ АЭП со съемом ВЧ-сигнала с линии контактным способом

**Comment by almkuznetsov** [comment]
@dpetruh
"С помощью анализатора спектра" - они все с помощью анализатора спектра, разделение будет скорее по эфиру или по линии. 
"С помощью акселерометра" - там не только акселерометр, лучше указать все три штуки

**Comment by almkuznetsov** [comment]
Еще раз перепроверить все названия и вписать физический принцип (он выделен в самом канале)

**Comment by almkuznetsov** [comment]
Есть каналы, у которых одним из физических принципов является паразитная генерация, но нет ни одного названия канала где она упоминается

**Comment by dpetruh** [comment]
По поводу паразитной генерации: она фигурирует в названии 2х из 3х каналов, в которых она присутствует
