### ISSUE TITLE
Вынести ПВЧГ в отдельный физический принцип

### ISSUE THREAD

**Issue by almkuznetsov** [almkuznetsov/bmstudemo#27]
Проставить там и в ВЧ АЭПе ссылки на то что это сходные каналы.

**Comment by almkuznetsov** [comment]
При этом ПВЧГ - это частный случай ВЧ АЭП

**Comment by nedomolkinaeyu** [comment]
вынесла физический принцип, отметила то, что это частный случай

**Comment by almkuznetsov** [comment]
1. Высокочастотное акустоэлектрическое преобразование теперь написано в физических принципах два раза, надо убрать дублирование
2. В файле "Высокочастотное акустоэлектрическое преобразование" текст цитаты начиная с "Данный технический канал утечки по своим физическим...." мы хотели вынести в отдельный физический принцип - "Паразитная генерация" и уже в нем написать, что он сходен с ВЧ АЭП, хотя упоминания в каналах тоже можно оставить, в этом ничего плохого нет

**Comment by nedomolkinaeyu** [comment]
1. убрано
2. добавлена паразитная генерация и дополнительно оставлено упоминание

**Comment by almkuznetsov** [comment]
По 53e8d44f05772f96f2c91a2407b1919e0ac41796
1. Создана карточка "Паразитная генерация", но на неё нет ссылки в графе "Физические принципы" на главной странице
2. Текст который вынесен в файл "Паразитная генерация" всё еще дублируется в файле "Высокочастотное акустоэлектрическое преобразование", его же вынесли в отдельную карточку, тут его не должно оставаться по идее
3. Карточка "Высокочастотное акустоэлектрическое преобразование" это по сути описание физического принципа, к чему там ссылка на другой физический принцип "Паразитная генерация", это же не канал, то есть наверное ссылка должна выглядеть как упоминание сходности.

**Comment by nedomolkinaeyu** [comment]
1. сделано
2. сделано
3. переделала

**Comment by almkuznetsov** [comment]
В карточке "Высокочастотное акустоэлектрическое преобразование" есть блок ссылок после "Если генератор паразитный:", можно там же и сделать ссылку на паразитную генерацию, а список конкретных каналов перенести в файл "Паразитная генерация"

**Comment by nedomolkinaeyu** [comment]
сделано
