### ISSUE TITLE
Устройство для обнаружения работы микрофона

### ISSUE THREAD

**Issue by almkuznetsov** [almkuznetsov/bmstudemo#30]
Интересное устройство, надо будет разобрать статью и включить в способы обнаружения закладок

https://xakep.ru/2022/09/13/ticktock/

**Comment by nedomolkinaeyu** [comment]
добавлены сведения об этом методе обнаружения

**Comment by almkuznetsov** [comment]
Статья на хакере к сожалению не является научным источником, нужно поискать оригинал научной публикации, если такая есть
Еще нужно будет подумать над тем к какому каналу это отнести, поэтому пока стоит оставить это открытым

**Comment by dpetruh** [comment]
Не удалось найти статьи на эту тему ни в русскоязычных, ни в иностранных источниках

**Comment by almkuznetsov** [comment]
Нашли, надо добавить

**Comment by nedomolkinaeyu** [comment]
сделано
