### ISSUE TITLE
В рамках одного канала может быть более одного физического принципа.

### ISSUE THREAD

**Issue by dpetruh** [almkuznetsov/bmstudemo#45]
Например, лазерный канал сочетает два физических прицнипа: колебания твердой среды и модуляция отраженного лазерного луча. Также за счет этого можно будет включить в нашу систему классификации скрытые каналы (к примеру, за счет создания сущности управляемого физического прицнипа)

**Comment by almkuznetsov** [comment]
В теории надо прогнать все каналы на предмет слишком большой широты описания физических принципов

**Comment by almkuznetsov** [comment]
Это уже частично сделано, например, в ВЧ АЭПе
