### ISSUE TITLE
Исправить мелкие косяки

### ISSUE THREAD

**Issue by almkuznetsov** [almkuznetsov/bmstudemo#48]
1. Методика си вч аэп - дураковский страница 533, а в книге 152 страницы
2. В критериях два раза ссылка на параметр защищённости ВЧН
3. Лазерный канал, ссылки на страницы 12-26 - там один абзац, он с какой из этих страниц?
4. Канал оптоволокна - опечатка в названии в слове акустической
5. Опять двойник Бузова в папке Заметки

**Comment by almkuznetsov** [comment]
6. Канал с акселерометром опечатка в слове информации

**Comment by nedomolkinaeyu** [comment]
1. непонятно, где 533 страница
![image](https://user-images.githubusercontent.com/106398080/203134070-a1e9bd09-eb31-47ed-a830-a3b7a8af87df.png)

**Comment by almkuznetsov** [comment]
3. Проблема-то не решена, просто убрать номер страницы это не выход
![image](https://user-images.githubusercontent.com/96069812/203502614-79dfe3a0-f2a5-4346-8763-fb4988d92f94.jpeg)

**Comment by nedomolkinaeyu** [comment]
Статья - это сайт с одной страницей, поэтому это решение было и принято.

**Comment by almkuznetsov** [comment]
Понял, хорошо
