### ISSUE TITLE
Почему существует электромагнитный канал?

### ISSUE THREAD

**Issue by almkuznetsov** [almkuznetsov/bmstudemo#5]
По идее его не должно быть, это же часть других каналов

**Comment by nedomolkinaeyu** [comment]
Сделано
Проверила, вся информация имеется у других каналов. Этот канал удален.

**Comment by almkuznetsov** [comment]
@nedomolkinaeyu ты удалила ссылки, но сам файлик "Электромагнитный канал" остался в папке "Заметки". Удали, пожалуйста

**Comment by almkuznetsov** [comment]
На самом деле это канал утечки акустической речевой информации за счет акустоэлектрического преобразования и ПЭМИ со съемом по эфиру
Надо добавить обратно всю информацию которая не дублируется и проставить ссылки на физические принципы

**Comment by nedomolkinaeyu** [comment]
добавила

**Comment by almkuznetsov** [comment]
У этого канала параметр и критерий защищенности такие же как у ПЭМИ. Нужно подумать, как их объединить, а не дублировать

**Comment by nedomolkinaeyu** [comment]
сделано

**Comment by nedomolkinaeyu** [comment]
сделано

**Comment by almkuznetsov** [comment]
Не сделано же, вот скрин этих двух каналов:
![image](https://user-images.githubusercontent.com/96069812/195034096-472274c1-3f3d-46d3-94b4-fbef8a0fb86d.jpeg)
Вот первая ссылка в каждом из каналов:
![image](https://user-images.githubusercontent.com/96069812/195038564-6678e413-a10c-496d-a894-b495b5606b53.jpeg)
Это же описание одного и того же параметра - зоны ЭМИ, просто разными словами. Их наоборот нужно объединить вместе в файле "Зона ЭМИ" и поставить ссылку на него в обоих каналах, чтобы не было дублирования
Вот критерий защищенности каждого из каналов:
![image](https://user-images.githubusercontent.com/96069812/195038862-636e1f5e-d3c6-4617-9788-aae1c13435da.jpeg)
Опять же одно и то же сравнение зоны ЭМИ с расстоянием до КЗ, по сути эта информация дублируется разными словами в двух разных файлах, хотя как раз этого и нужно избегать

**Comment by almkuznetsov** [comment]
Еще касательно этого канала:
- Хорошо что определение речевого сигнала вынесено в отдельный файл, но там во-первых потерялась ссылка на учебник, откуда это взято, а во-вторых получается что определение написано два раза - само в себе и в этой другой карточке. Это то дублирование, которого нужно избегать

**Comment by nedomolkinaeyu** [comment]
сделано
