### ISSUE TITLE
Все основные характеристики и физические принципы должны быть отдельными карточками, а в карточке канала должны быть ссылки на них

### ISSUE THREAD

**Issue by almkuznetsov** [almkuznetsov/bmstudemo#9]
Так может получиться, что у многих каналов одинаковые принципы и одинаковые параметры - тоже можно проверить

**Comment by almkuznetsov** [comment]
Случайно отнес часть коммитов для решения этой проблемы в #19 
df2f2cfbe514ceb2ca9d94c9f421fabcedd8d96f
414831636d7d44e0200c96b7374c8429086e5104
13cf9408c6cb893888416b2cc1076f967a74008b

**Comment by nedomolkinaeyu** [comment]
сделано там, где есть и критерий и физический принцип

**Comment by almkuznetsov** [comment]
вот в этом коммите -08b6352b73222209cec19ae59af99b16ba6b7cc0
Созданы карточки "Неравномерность потребления тока" и "Канал отходящих коммуникаций"
1. "Неравномерность потребления тока"
Там содержится просто информация по критериям для канала, но не сами критерии - на них идут ссылки. Вопрос почему тогда эта карточка во-первых существует (можно было просто этот абзац вставить в сам канал НПТ) и во-вторых почему она в общем файле лежит по заголовком "Критерии", хотя критериев там нет - для них есть отдельные карточки, которые как раз есть в "Критериях"
2. "Канал отходящих коммуникаций"
То же самое - критериев здесь нет, только ссылки на них. Но вот он почему-то отнесен в раздел "Параметры", хотя и параметров там тоже нет, это информация про конкретный канал

Если я неправильно понимаю, то объясните, пожалуйста

**Comment by nedomolkinaeyu** [comment]
сделано
